# Example docker-compose.yml
services:
  exhibition-proxy:
    image: "ghcr.io/phoebesoftware/exhibition-proxy:latest"
    ports:
      - "12345:12345"
    # Its very useful to bind the data folder because the proxy-settings.yml is in /usr/local/app/data
    volumes:
      - ./data:/data
    environment:
      # Default is /data but you can change it here if you desire
      # Note this changes the path in your docker container not on the root
      - DATA_PATH=/data